<?php

namespace Modules\User\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use DB;

class SeedUserFieldOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $data = array(
                        array("user_field_id" => 2,"option"=>"Baby food"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>1,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>2,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Frozen","parent"=>2,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Perishable","parent"=>2,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>2,"head"=>0),
                            array("user_field_id" => 2,"option"=>"Properties","parent"=>1,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>7,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>7,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Bakery & Snacks"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>21,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>22,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>22,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>22,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>22,"head"=>0),
                            array("user_field_id" => 2,"option"=>"Properties","parent"=>21,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>27,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>27,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Baking mixes"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>41,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>42,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>42,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>42,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>42,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>41,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>47,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>47,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Base Ingredients"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>61,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>62,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>62,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>62,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>62,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>61,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>67,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>67,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Beer"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>81,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>82,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>82,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>82,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>82,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>81,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>87,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>87,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Cereals & Legumes"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>101,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>102,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>102,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>102,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>102,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>101,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>107,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>107,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Cheese"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>121,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>122,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>122,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>122,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>122,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>121,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>127,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>127,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Coffee & Tea"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>141,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>142,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>142,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>142,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>142,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>141,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>147,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>147,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Coffee Beans/Pods/Capsules"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>161,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>162,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>162,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>162,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>162,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>161,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>167,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>167,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Confectionary & Sweets"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>181,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>182,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>182,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>182,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>182,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>181,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>187,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>187,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Condiments"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>201,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>202,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>202,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>202,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>202,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>201,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>207,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>207,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Dairy"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>221,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>222,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>222,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>222,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>222,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>221,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>227,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>227,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Fruits & Vegetables"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>241,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>242,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>242,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>242,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>242,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>241,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>247,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>247,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Gelato"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>261,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>262,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>262,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>262,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>262,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>261,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>267,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>267,"head"=>0),


                        array("user_field_id" => 2,"option"=>"Gelato"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>281,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>282,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>282,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>282,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>282,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>281,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>287,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>287,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Honey"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>301,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>302,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>302,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>302,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>302,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>301,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>307,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>307,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Nuts and seed"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>321,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>322,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>322,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>322,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>322,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>321,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>327,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>327,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Meat & Salumi"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>341,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>342,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>342,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>342,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>342,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>341,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>347,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>347,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Mushrooms & Truffles"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>361,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>362,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>362,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>362,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>362,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>361,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>367,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>367,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Oil & Vinegar"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>381,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>382,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>382,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>382,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>382,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>381,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>387,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>387,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Olives"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>401,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>402,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>402,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>402,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>402,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>401,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>407,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>407,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Pasta & Rice"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>421,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>422,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>422,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>422,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>422,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>421,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>427,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>427,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Pizza Mix"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>441,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>442,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>442,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>442,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>442,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>441,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>447,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>447,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Preserves & Sauces"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>461,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>462,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>462,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>462,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>462,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>461,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>467,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>467,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Ready Meals/Soups"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>481,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>482,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>482,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>482,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>482,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>481,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>487,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>487,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Seafood"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>501,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>502,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>502,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>502,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>502,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>501,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>507,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>507,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Spirits"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>521,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>522,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>522,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>522,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>522,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>521,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>527,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>527,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Spreads & Jams"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>541,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>542,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>542,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>542,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>542,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>541,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>547,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>547,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Juices, Soft Drinks, Water"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>561,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>562,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>562,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>562,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>562,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>561,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>567,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>567,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Wine"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>581,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>582,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>582,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>582,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>582,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>581,"head"=>1),
                                    array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"GMO free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Organic","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Vegan","parent"=>587,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Others","parent"=>587,"head"=>0),

                        /*array("user_field_id" => 13,"option"=>"USA"),
                        array("user_field_id" => 13,"option"=>"Italy"),*/


                        // array("user_field_id" => 13,"option"=>"Abruzzo","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Valley","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Apulia","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Basilicata","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Calabria","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Campania","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Emilia-Romagna","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Friuli-Venezia Giulia","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Lazio","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Liguria","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Lombardy","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Marche","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Molise","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Piedmont","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Sardinia","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Sicily","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Trentino-South Tyrol","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Tuscany","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Umbria","parent"=>602,"head"=>0),
                        // array("user_field_id" => 13,"option"=>"Veneto","parent"=>602,"head"=>0),

                        array("user_field_id" => 3,"option"=>"Abruzzo"),
                        array("user_field_id" => 3,"option"=>"Valley"),
                        array("user_field_id" => 3,"option"=>"Apulia"),
                        array("user_field_id" => 3,"option"=>"Basilicata"),
                        array("user_field_id" => 3,"option"=>"Calabria"),
                        array("user_field_id" => 3,"option"=>"Campania"),
                        array("user_field_id" => 3,"option"=>"Emilia-Romagna"),
                        array("user_field_id" => 3,"option"=>"Friuli-Venezia Giulia"),
                        array("user_field_id" => 3,"option"=>"Lazio"),
                        array("user_field_id" => 3,"option"=>"Liguria"),
                        array("user_field_id" => 3,"option"=>"Lombardy"),
                        array("user_field_id" => 3,"option"=>"Marche"),
                        array("user_field_id" => 3,"option"=>"Molise"),
                        array("user_field_id" => 3,"option"=>"Piedmont"),
                        array("user_field_id" => 3,"option"=>"Sardinia"),
                        array("user_field_id" => 3,"option"=>"Sicily"),
                        array("user_field_id" => 3,"option"=>"Trentino-South Tyrol"),
                        array("user_field_id" => 3,"option"=>"Tuscany"),
                        array("user_field_id" => 3,"option"=>"Umbria"),
                        array("user_field_id" => 3,"option"=>"Veneto"),

                        array("user_field_id" => 4,"option"=>"Yes"),
                        array("user_field_id" => 4,"option"=>"No"),

                        array("user_field_id" => 5,"option"=>"Yes"),
                        array("user_field_id" => 5,"option"=>"No"),

                        array("user_field_id" => 6,"option"=>"Yes"),
                        array("user_field_id" => 6,"option"=>"No"),

                        array("user_field_id" => 8,"option"=>"Chicago"),

                        array("user_field_id" => 9,"option"=>"Pick up"),
                        array("user_field_id" => 9,"option"=>"Delivery"), 

                        array("user_field_id" => 10,"option"=>"Cafe"),
                        array("user_field_id" => 10,"option"=>"Casual"),
                        array("user_field_id" => 10,"option"=>"Enoteca"),
                        array("user_field_id" => 10,"option"=>"Family Style"),
                        array("user_field_id" => 10,"option"=>"Fine Dining"),
                        array("user_field_id" => 10,"option"=>"Pizzeria"),
                        array("user_field_id" => 10,"option"=>"Regional Cuisine"),
                        array("user_field_id" => 10,"option"=>"Trattoria/Osteria"),

                        array("user_field_id" => 11,"option"=>"Wine"),
                        array("user_field_id" => 11,"option"=>"Food"),
                        array("user_field_id" => 11,"option"=>"Wine and Food"),
                        
                        array("user_field_id" => 12,"option"=>"Blog Author"),
                        array("user_field_id" => 12,"option"=>"Book Author"),
                        array("user_field_id" => 12,"option"=>"Brand Ambassador"),
                        array("user_field_id" => 12,"option"=>"Chef"),
                        array("user_field_id" => 12,"option"=>"Chef-Owner"),
                        array("user_field_id" => 12,"option"=>"Culinary Artist"),
                        array("user_field_id" => 12,"option"=>"Culinary Expert"),
                        array("user_field_id" => 12,"option"=>"Culinary Judge"),
                        array("user_field_id" => 12,"option"=>"Food Photographer"),
                        array("user_field_id" => 12,"option"=>"Nutritionist"),
                        array("user_field_id" => 12,"option"=>"TV Personality"),

                        array("user_field_id" => 14,"option"=>"Alysei Selections"),
                        array("user_field_id" => 14,"option"=>"Architectural & Historic Toursoth"),
                        array("user_field_id" => 14,"option"=>"Art Tours"),
                        array("user_field_id" => 14,"option"=>"Biking Tours"),
                        array("user_field_id" => 14,"option"=>"Classes & Workshops"),
                        array("user_field_id" => 14,"option"=>"Classical Italy"),
                        array("user_field_id" => 14,"option"=>"Cruise, Sailing & Boat Tours"),
                        array("user_field_id" => 14,"option"=>"Hiking Tours"),
                        array("user_field_id" => 14,"option"=>"Italian Islands"),
                        array("user_field_id" => 14,"option"=>"Private & Custom Tours"),
                        array("user_field_id" => 14,"option"=>"Walking Tours"),
                        array("user_field_id" => 14,"option"=>"Winter Sport Tours"),



                        array("user_field_id" => 20,"option"=>"USA"),
                        array("user_field_id" => 20,"option"=>"Italy"),

                        array("user_field_id" => 21,"option"=>"10%"),
                        array("user_field_id" => 21,"option"=>"20%"),
                        array("user_field_id" => 21,"option"=>"30%"),

                        array("user_field_id" => 22,"option"=>"10%"),
                        array("user_field_id" => 22,"option"=>"20%"),
                        array("user_field_id" => 22,"option"=>"30%"),

                        array("user_field_id" => 23,"option"=>"Riverdale"),
                        array("user_field_id" => 23,"option"=>"lincoln Park"),

                        array("user_field_id" => 24,"option"=>"Abruzzo"),
                        array("user_field_id" => 24,"option"=>"Valley"),
                        array("user_field_id" => 24,"option"=>"Apulia"),
                        array("user_field_id" => 24,"option"=>"Basilicata"),
                        array("user_field_id" => 24,"option"=>"Calabria"),
                        array("user_field_id" => 24,"option"=>"Campania"),
                        array("user_field_id" => 24,"option"=>"Emilia-Romagna"),
                        array("user_field_id" => 24,"option"=>"Friuli-Venezia Giulia"),
                        array("user_field_id" => 24,"option"=>"Lazio"),
                        array("user_field_id" => 24,"option"=>"Liguria"),
                        array("user_field_id" => 24,"option"=>"Lombardy"),
                        array("user_field_id" => 24,"option"=>"Marche"),
                        array("user_field_id" => 24,"option"=>"Molise"),
                        array("user_field_id" => 24,"option"=>"Piedmont"),
                        array("user_field_id" => 24,"option"=>"Sardinia"),
                        array("user_field_id" => 24,"option"=>"Sicily"),
                        array("user_field_id" => 24,"option"=>"Trentino-South Tyrol"),
                        array("user_field_id" => 24,"option"=>"Tuscany"),
                        array("user_field_id" => 24,"option"=>"Umbria"),
                        array("user_field_id" => 24,"option"=>"Veneto"),

                        array("user_field_id" => 26,"option"=>"Abruzzo"),
                        array("user_field_id" => 26,"option"=>"Valley"),
                        array("user_field_id" => 26,"option"=>"Apulia"),
                        array("user_field_id" => 26,"option"=>"Basilicata"),
                        array("user_field_id" => 26,"option"=>"Calabria"),
                        array("user_field_id" => 26,"option"=>"Campania"),
                        array("user_field_id" => 26,"option"=>"Emilia-Romagna"),
                        array("user_field_id" => 26,"option"=>"Friuli-Venezia Giulia"),
                        array("user_field_id" => 26,"option"=>"Lazio"),
                        array("user_field_id" => 26,"option"=>"Liguria"),
                        array("user_field_id" => 26,"option"=>"Lombardy"),
                        array("user_field_id" => 26,"option"=>"Marche"),
                        array("user_field_id" => 26,"option"=>"Molise"),
                        array("user_field_id" => 26,"option"=>"Piedmont"),
                        array("user_field_id" => 26,"option"=>"Sardinia"),
                        array("user_field_id" => 26,"option"=>"Sicily"),
                        array("user_field_id" => 26,"option"=>"Trentino-South Tyrol"),
                        array("user_field_id" => 26,"option"=>"Tuscany"),
                        array("user_field_id" => 26,"option"=>"Umbria"),
                        array("user_field_id" => 26,"option"=>"Veneto"),


                        array("user_field_id" => 27,"option"=>"Intrest 1","parent"=>0,"head"=>0),
                        array("user_field_id" => 27,"option"=>"Intrest 2","parent"=>0,"head"=>0),


                );

        foreach ($data as $key => $value) {
            DB::table('user_field_options')->insert($value);
        }
    }
}
