<?php

namespace Modules\User\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use DB;

class SeedUserFieldOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $data = array(
                        array("user_field_id" => 2,"option"=>"Baby food"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>1,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Frozen","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Perishable","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Properties","parent"=>1,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>1,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>1,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Bakery & Snacks"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>21,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>21,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>21,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>21,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>21,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>21,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>21,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>21,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Baking mixes"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>41,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>41,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>41,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>41,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>41,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>41,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>41,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>41,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Base Ingredients"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>61,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>61,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>61,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>61,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>61,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>61,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>61,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>61,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Beer"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>81,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>81,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>81,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>81,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>81,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>81,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>81,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>81,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Cereals & Legumes"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>101,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>101,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>101,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>101,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>101,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>101,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>101,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>101,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Cheese"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>121,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>121,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>121,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>121,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>121,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>121,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>121,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>121,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Coffee & Tea"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>141,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>141,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>141,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>141,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>141,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>141,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>141,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>141,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Coffee Beans/Pods/Capsules"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>161,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>161,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>161,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Confectionary & Sweets"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>161,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>161,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>161,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>161,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>161,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Condiments"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>181,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>181,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>181,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>181,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>181,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>181,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>181,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>181,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Dairy"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>201,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>201,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>201,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>201,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>201,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>201,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>201,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>201,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Fruits & Vegetables"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>221,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>221,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>221,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>221,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>221,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>221,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>221,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>221,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Gelato"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>241,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>241,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>241,"head"=>0),


                        array("user_field_id" => 2,"option"=>"Gelato"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>241,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>241,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>241,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>241,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>241,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Honey"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>261,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>261,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>261,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>261,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>261,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>261,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>261,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>261,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Nuts and seed"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>281,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>281,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>281,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>281,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>281,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>281,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>281,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>281,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Meat & Salumi"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>301,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>301,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>301,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>301,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>301,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>301,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>301,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>301,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Mushrooms & Truffles"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>321,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>321,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>321,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>321,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>321,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>321,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>321,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>321,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Oil & Vinegar"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>341,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>341,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>341,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>341,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>341,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>341,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>341,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>341,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Olives"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>361,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>361,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>361,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>361,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>361,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>361,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>361,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>361,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Pasta & Rice"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>381,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>381,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>381,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>381,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>381,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>381,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>381,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>381,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Pizza Mix"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>401,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>401,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>401,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>401,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>401,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>401,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>401,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>401,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Preserves & Sauces"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>421,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>421,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>421,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>421,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>421,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>421,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>421,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>421,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Ready Meals/Soups"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>441,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>441,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>441,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>441,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>441,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>441,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>441,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>441,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Seafood"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>461,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>461,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>461,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>461,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>461,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>461,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>461,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>461,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Spirits"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>481,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>481,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>481,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>481,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>481,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>481,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>481,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>481,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Spreads & Jams"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>501,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>501,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>501,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>501,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>501,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>501,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>501,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>501,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Juices, Soft Drinks, Water"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>521,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>521,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>521,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>521,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>521,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>521,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>521,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>521,"head"=>0),

                        array("user_field_id" => 2,"option"=>"Wine"),
                            array("user_field_id" => 2,"option"=>"Conservation method","parent"=>541,"head"=>1),
                                array("user_field_id" => 2,"option"=>"Canned goods","parent"=>541,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Frozen","parent"=>541,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Perishable","parent"=>541,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Shelf Stable","parent"=>541,"head"=>0),
                                    array("user_field_id" => 2,"option"=>"Properties","parent"=>541,"head"=>1),

                            array("user_field_id" => 2,"option"=>"Allergen Free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Gluten Free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"GMO free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Lactose Free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Cholesterol","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Low Sodium/Sodium Free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Organic","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Palm Oil Free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Preservatives Free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Rich in Omega 3-6","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Sugar Free","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Vegan","parent"=>541,"head"=>0),
                                array("user_field_id" => 2,"option"=>"Others","parent"=>541,"head"=>0),

                        array("user_field_id" => 3,"option"=>"Abruzzo"),
                        array("user_field_id" => 3,"option"=>"Valley"),
                        array("user_field_id" => 3,"option"=>"Apulia"),
                        array("user_field_id" => 3,"option"=>"Basilicata"),
                        array("user_field_id" => 3,"option"=>"Calabria"),
                        array("user_field_id" => 3,"option"=>"Campania"),
                        array("user_field_id" => 3,"option"=>"Emilia-Romagna"),
                        array("user_field_id" => 3,"option"=>"Friuli-Venezia Giulia"),
                        array("user_field_id" => 3,"option"=>"Lazio"),
                        array("user_field_id" => 3,"option"=>"Liguria"),
                        array("user_field_id" => 3,"option"=>"Lombardy"),
                        array("user_field_id" => 3,"option"=>"Marche"),
                        array("user_field_id" => 3,"option"=>"Molise"),
                        array("user_field_id" => 3,"option"=>"Piedmont"),
                        array("user_field_id" => 3,"option"=>"Sardinia"),
                        array("user_field_id" => 3,"option"=>"Sicily"),
                        array("user_field_id" => 3,"option"=>"Trentino-South Tyrol"),
                        array("user_field_id" => 3,"option"=>"Tuscany"),
                        array("user_field_id" => 3,"option"=>"Umbria"),
                        array("user_field_id" => 3,"option"=>"Veneto"),

                        array("user_field_id" => 4,"option"=>"Yes"),
                        array("user_field_id" => 4,"option"=>"No"),

                        array("user_field_id" => 5,"option"=>"Yes"),
                        array("user_field_id" => 5,"option"=>"No"),

                        array("user_field_id" => 6,"option"=>"Yes"),
                        array("user_field_id" => 6,"option"=>"No"),

                        array("user_field_id" => 8,"option"=>"Chicago"),

                        array("user_field_id" => 9,"option"=>"Pick up"),
                        array("user_field_id" => 9,"option"=>"Delivery"), 

                        array("user_field_id" => 10,"option"=>"Cafe"),
                        array("user_field_id" => 10,"option"=>"Casual"),
                        array("user_field_id" => 10,"option"=>"Enoteca"),
                        array("user_field_id" => 10,"option"=>"Family Style"),
                        array("user_field_id" => 10,"option"=>"Fine Dining"),
                        array("user_field_id" => 10,"option"=>"Pizzeria"),
                        array("user_field_id" => 10,"option"=>"Regional Cuisine"),
                        array("user_field_id" => 10,"option"=>"Trattoria/Osteria"),

                        array("user_field_id" => 11,"option"=>"Wine"),
                        array("user_field_id" => 11,"option"=>"Food"),
                        array("user_field_id" => 11,"option"=>"Both"),
                        
                        array("user_field_id" => 12,"option"=>"Blog Author"),
                        array("user_field_id" => 12,"option"=>"Book Author"),
                        array("user_field_id" => 12,"option"=>"Brand Ambassador"),
                        array("user_field_id" => 12,"option"=>"Chef"),
                        array("user_field_id" => 12,"option"=>"Chef-Owner"),
                        array("user_field_id" => 12,"option"=>"Culinary Artist"),
                        array("user_field_id" => 12,"option"=>"Culinary Expert"),
                        array("user_field_id" => 12,"option"=>"Culinary Judge"),
                        array("user_field_id" => 12,"option"=>"Food Photographer"),
                        array("user_field_id" => 12,"option"=>"Nutritionist"),
                        array("user_field_id" => 12,"option"=>"TV Personality"),

                        array("user_field_id" => 14,"option"=>"Alysei Selections"),
                        array("user_field_id" => 14,"option"=>"Architectural & Historic Toursoth"),
                        array("user_field_id" => 14,"option"=>"Art Tours"),
                        array("user_field_id" => 14,"option"=>"Biking Tours"),
                        array("user_field_id" => 14,"option"=>"Classes & Workshops"),
                        array("user_field_id" => 14,"option"=>"Classical Italy"),
                        array("user_field_id" => 14,"option"=>"Cruise, Sailing & Boat Tours"),
                        array("user_field_id" => 14,"option"=>"Hiking Tours"),
                        array("user_field_id" => 14,"option"=>"Italian Islands"),
                        array("user_field_id" => 14,"option"=>"Private & Custom Tours"),
                        array("user_field_id" => 14,"option"=>"Walking Tours"),
                        array("user_field_id" => 14,"option"=>"Winter Sport Tours"),

                        array("user_field_id" => 13,"option"=>"USA"),
                        array("user_field_id" => 13,"option"=>"Italy"),
                        

                );

        foreach ($data as $key => $value) {
            DB::table('user_field_options')->insert($value);
        }
    }
}
